/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_ndk_NDKExam */

#ifndef _Included_org_example_ndk_NDKExam
#define _Included_org_example_ndk_NDKExam
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_ndk_NDKExam
 * Method:    switchdriveropen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_NDKExam_switchdriveropen
  (JNIEnv *, jobject);

/*
 * Class:     org_example_ndk_NDKExam
 * Method:    switchdriverclose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_NDKExam_switchdriverclose
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_example_ndk_NDKExam
 * Method:    driverwrite
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_NDKExam_driverwrite
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_example_ndk_NDKExam
 * Method:    fndwrite
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_NDKExam_fndwrite
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_example_ndk_NDKExam
 * Method:    switchread
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_NDKExam_switchread
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
