/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_ndk_NDKExam_BackThread */

#ifndef _Included_org_example_ndk_NDKExam_BackThread
#define _Included_org_example_ndk_NDKExam_BackThread
#ifdef __cplusplus
extern "C" {
#endif
#undef org_example_ndk_NDKExam_BackThread_MIN_PRIORITY
#define org_example_ndk_NDKExam_BackThread_MIN_PRIORITY 1L
#undef org_example_ndk_NDKExam_BackThread_NORM_PRIORITY
#define org_example_ndk_NDKExam_BackThread_NORM_PRIORITY 5L
#undef org_example_ndk_NDKExam_BackThread_MAX_PRIORITY
#define org_example_ndk_NDKExam_BackThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
